### ISSUE TITLE
Unable to build for windows

### ISSUE THREAD

**Issue by phileagleson** [smacker/go-tree-sitter#120]
When I try to build this library with windows as a target I'm getting several errors in iter.go:

```
➜ GOARCH=amd64 GOOS=windows go build .
 github.com/smacker/go-tree-sitter
./iter.go:17:18: undefined: Node
./iter.go:21:21: undefined: Node
./iter.go:25:20: undefined: Node
./iter.go:30:26: undefined: Node
./iter.go:34:20: undefined: Node
./iter.go:38:32: undefined: Node
./iter.go:43:9: undefined: Node
./iter.go:46:18: undefined: Node
./iter.go:68:40: undefined: Node
```

When building for linux, the build succeeds as expected. I can see 'Node' is defined in bindings.go and both iter.go and bindings.go are part of the sitter package so I''m not sure why this error occurs.

**Comment by phileagleson** [comment]
In case this helps anyone else - I was able to fix this by installing a cross-compile version of gcc. I'm using Arch, but the package names should be similar on other distros:
install : 
  * gcc-multilib
  * mingw-w64-gcc

set additional flags when building:

```
	GOARCH=amd64 GOOS=windows \
           CGO_ENABLED=1 \
           CXX=x86_64-w64-mingw32-g++ \
           CC=x86_64-w64-mingw32-gcc \
	   go build -o bin/appName64.exe cmd/app/main.go 

```

**Comment by phileagleson** [comment]
After further testing, the previous method, still had issues. The app would compile fine, but when running on a Windows machine, it was missing some required dll's for the c standard library. The easiest way I found to get around this was surprisingly to use zig to compile. 

https://dev.to/kristoff/zig-makes-go-cross-compilation-just-work-29ho

Using this method, I get a static binary that works on Windows and doesn't require any additional dependencies

**Comment by zimmski** [comment]
Sorry i overlooked this thread even though we can add our experience to it. (Vacation are bad for your mail queue!)

We are building https://symflower.com for Linux/MacOS/Windows for different architectures. For Windows we are using https://github.com/mstorsjo/llvm-mingw which works great! I had multiple looks into Zig (did not look into the latest 0.11 release though!) and i had smaller compilation problems that were solvable but the binaries crashed in various scenarios. I tracked down most of them in open issues, don't know their current state, i just wanted to note: if your binary crashes, might be because of compiling with Zig, so please let them know.

One option that we are using is `-tags=netgo,osusergo`.

Your original problem https://github.com/smacker/go-tree-sitter/issues/120#issue-1866161923 i can explain. AFAIK if you are cross compiling, CGO is disabled, so you need to explicitly enable it with `CGO_ENABLED=1` and that you did :-)

**Comment by Owatron** [comment]
I have the same issue , can you please help me out?

**Comment by Borwe** [comment]
Whats the solution for those on Windows?

**Comment by zimmski** [comment]
> I have the same issue , can you please help me out?

@Owatron @Borwe i guess https://www.mingw-w64.org/ is a compiler for Windows?

**Comment by thesayyn** [comment]
@phileagleson can you reopen this issue as this is a valid issue that haven't been solved?  
Library should build just fine with msvc, as there is no reason it shouldn't.

**Comment by phileagleson** [comment]
@thesayyn I don't believe this library is still needed. Tree-sitter has official go bindings now:
 
https://github.com/tree-sitter/go-tree-sitter

When running tree-siiter generate from the CLI, it will automatically generate a binding.go for that language now.

That being said, i haven't tested the official version, it's possible it may have a similar issue. Please let me know if you still believe this needs reopened.
